name: flutter_lab_sheet_2
description: BCA Flutter Lab Sheet 2 - Basic Flutter Widgets and UI Design
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
